# Generated by Django 3.0.5 on 2022-04-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidente',
            name='extorsion',
        ),
        migrations.AddField(
            model_name='incidente',
            name='cuentaExtorsionador',
            field=models.CharField(default='Sin cuenta', max_length=60, verbose_name='cuenta'),
        ),
        migrations.AddField(
            model_name='incidente',
            name='deposito',
            field=models.FloatField(default=0, verbose_name='Cantidad depositado'),
        ),
        migrations.AddField(
            model_name='incidente',
            name='nombreExtorsionador',
            field=models.CharField(default='Desconocido', max_length=60, verbose_name='Nombre del extorsionador'),
        ),
        migrations.AddField(
            model_name='incidente',
            name='numeroExtorsionador',
            field=models.CharField(default='Desconocido', max_length=60, verbose_name='numero'),
        ),
        migrations.DeleteModel(
            name='Extorsion',
        ),
    ]
